name: Windows – Litemanager

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building…
    runs-on: windows-latest
    steps:
      - name: Downloading & Installing Essentials
        shell: powershell
        run: |
          Invoke-WebRequest -Uri "https://gitlab.com/chamod12/lm_win-10_github_rdp/-/raw/main/Downloads.bat" -OutFile "Downloads.bat"
          cmd /c Downloads.bat

      - name: Connect to LiteManager
        shell: cmd
        run: show.bat

      - name: Time Counter
        shell: cmd
        run: loop.bat
